- name: installing remi release
  ansible.builtin.command: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
- name: enabling remi 6.2
  ansible.builtin.command: dnf module enable redis:remi-6.2 -y
- name: installing redis
  ansible.builtin.dnf:
    name: redis
    state: present
- name: update listener address in redis conf file
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: starting and enabling redis
  ansible.builtin.systemd_service:
    name: redis
    state: started
    enabled: true