- name: copying mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
- name: installing mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present
- name: enabling and starting mongodb 
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
- name: updating listener address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: restarting mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted