- name: adding roboshop user
  ansible.builtin.user:
    name: roboshop
- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: "download {{component}} code to tmp directory"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp
- name: unzipping code in app directory
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes