- name: installing mysql
  ansible.builtin.dnf:
    name: mysql
    state: present
- name: checking whether shipping data exists or not
  ansible.builtin.shell: mysql -h mysql.sowjanyaaws.online -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='cities'"
  register: schema
- name: print output
  ansible.builtin.debug:
    msg: "schema output:{{schema}}"
- name: loading cities data
  ansible.builtin.shell: mysql -h mysql.sowjanyaaws.online -uroot -p{{mysql_password}} < /app/schema/shipping.sql
  when: schema.stdout != "1"
