- name: installing packages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop:
  - python36 
  - gcc 
  - python3-devel 
- name: installing dependancies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app